/*
Copyright (c) 2024-2025 Stephen Gold

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */
package com.github.stephengold.joltjni;

import com.github.stephengold.joltjni.readonly.ConstShape;
import com.github.stephengold.joltjni.readonly.ConstShapeSettings;
import com.github.stephengold.joltjni.readonly.QuatArg;
import com.github.stephengold.joltjni.readonly.Vec3Arg;
import com.github.stephengold.joltjni.vhacd.ConvexHull;
import java.nio.FloatBuffer;
import java.util.Collection;

/**
 * Settings used to construct a {@code CompoundShape}.
 *
 * @author Stephen Gold sgold@sonic.net
 */
abstract public class CompoundShapeSettings extends ShapeSettings {
    // *************************************************************************
    // constructors

    /**
     * Instantiate a settings object with no native object assigned.
     */
    CompoundShapeSettings() {
    }

    /**
     * Instantiate with the specified native object assigned but not owned.
     *
     * @param settingsVa the virtual address of the native object to assign (not
     * zero)
     */
    CompoundShapeSettings(long settingsVa) {
        super(settingsVa);
    }
    // *************************************************************************
    // new methods exposed

    /**
     * Add a collection of convex hulls generated by V-HACD.
     *
     * @param hulls the hulls to add (not null, unaffected)
     */
    public void addHulls(Collection<ConvexHull> hulls) {
        for (ConvexHull hull : hulls) {
            FloatBuffer points = hull.getPointsAsBuffer();
            int numFloats = points.capacity();
            int numPoints = numFloats / 3;
            ConvexHullShapeSettings childSettings
                    = new ConvexHullShapeSettings(numPoints, points);
            addShape(0f, 0f, 0f, childSettings);
        }
    }

    /**
     * Add the specified sub-shape at the specified offset.
     *
     * @param xOffset the desired X offset for the sub-shape
     * @param yOffset the desired Y offset for the sub-shape
     * @param zOffset the desired Z offset for the sub-shape
     * @param subShape the sub-shape to add (not null)
     */
    public void addShape(
            float xOffset, float yOffset, float zOffset, ConstShape subShape) {
        long settingsVa = va();
        float rotW = 1f;
        float rotX = 0f;
        float rotY = 0f;
        float rotZ = 0f;
        long subShapeVa = subShape.targetVa();
        addShape(settingsVa, xOffset, yOffset, zOffset,
                rotX, rotY, rotZ, rotW, subShapeVa);
    }

    /**
     * Add the specified sub-shape at the specified offset.
     *
     * @param xOffset the desired X offset for the sub-shape
     * @param yOffset the desired Y offset for the sub-shape
     * @param zOffset the desired Z offset for the sub-shape
     * @param subSettings the desired sub-shape settings (not null)
     */
    public void addShape(float xOffset, float yOffset, float zOffset,
            ConstShapeSettings subSettings) {
        long settingsVa = va();
        float rotW = 1f;
        float rotX = 0f;
        float rotY = 0f;
        float rotZ = 0f;
        long subSettingsVa = subSettings.targetVa();
        addShapeSettings(settingsVa, xOffset, yOffset, zOffset,
                rotX, rotY, rotZ, rotW, subSettingsVa);
    }

    /**
     * Add the specified sub-shape at the specified position.
     *
     * @param offset the desired offset for the sub-shape (not null, unaffected)
     * @param rotation the desired rotation for the sub-shape ((not null, not
     * zero, unaffected)
     * @param subShape the sub-shape to add (not null)
     */
    public void addShape(
            Vec3Arg offset, QuatArg rotation, ConstShape subShape) {
        long settingsVa = va();
        float offsetX = offset.getX();
        float offsetY = offset.getY();
        float offsetZ = offset.getZ();
        float rotW = rotation.getW();
        float rotX = rotation.getX();
        float rotY = rotation.getY();
        float rotZ = rotation.getZ();
        long subShapeVa = subShape.targetVa();
        addShape(settingsVa, offsetX, offsetY, offsetZ,
                rotX, rotY, rotZ, rotW, subShapeVa);
    }

    /**
     * Add the specified sub-shape at the specified position.
     *
     * @param offset the desired offset for the sub-shape (not null, unaffected)
     * @param rotation the desired rotation for the sub-shape (not null, not
     * zero, unaffected)
     * @param subSettings the desired sub-shape settings (not null)
     */
    public void addShape(
            Vec3Arg offset, QuatArg rotation, ConstShapeSettings subSettings) {
        long settingsVa = va();
        float offsetX = offset.getX();
        float offsetY = offset.getY();
        float offsetZ = offset.getZ();
        float rotW = rotation.getW();
        float rotX = rotation.getX();
        float rotY = rotation.getY();
        float rotZ = rotation.getZ();
        long subSettingsVa = subSettings.targetVa();
        addShapeSettings(settingsVa, offsetX, offsetY, offsetZ,
                rotX, rotY, rotZ, rotW, subSettingsVa);
    }
    // *************************************************************************
    // native private methods

    native private static void addShape(long settingsVa, float offsetX,
            float offsetY, float offsetZ, float rotX, float rotY, float rotZ,
            float rotW, long subShapeVa);

    native private static void addShapeSettings(long settingsVa, float offsetX,
            float offsetY, float offsetZ, float rotX, float rotY, float rotZ,
            float rotW, long subSettingsVa);
}
